name: Docker CI/CD for Python Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub using GitHub secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image to Docker Hub
      - name: Build Docker image
        run: |
          docker build -t my-python-app .

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-python-app:latest ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest

      # Deploy Docker image locally on your laptop (this step runs locally, not on GitHub Actions)
      - name: Run Docker container locally
        run: |
          docker run -d --name my-python-app -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest
        if: github.event_name == 'push'
