name: Docker CI/CD for Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest

      # Step 5: Deploy to the server (You can customize this for your setup)
      # Example: SSH into a remote server and run docker-compose or similar
      - name: Deploy to server
        run: |
          ssh user@server "docker pull ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest && docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest"
